### ISSUE TITLE
我的声卡驱动出了问题

### ISSUE THREAD

**Issue by intLyc** [ZGGSONG/HP-OMEN-15-ax214TX-Hackintosh#2]
谢谢大佬，已经装好了10.15，我的型号是暗影精灵2pro i5-7300HQ，我用10.15的EFI文件刚装上的时候是有声音的，但是今天突然没有了，我做过的有：更新系统（10.15.2->10.15.3，更新完好像还有声音)、启动睡眠并进入系统（忘记是不是这个之后没声音），现在就一直没有声音了。有时候能检测出来声卡驱动，可以用耳机，但是不能用内置音频；有时候连驱动都没识别，无法调音量，插耳机也没用。

**Comment by ZGGSONG** [comment]
打开config文件，重新注入声卡id，就把上边的28重新输入，保存并重启，应该就可以解决了

**Comment by intLyc** [comment]
我试了好多次重新注入，还是不行

**Comment by ZGGSONG** [comment]
把你原本的efi删了，重新把这个efi放进去试试，我用的就是10.15.3，没有问题的

**Comment by intLyc** [comment]
现在可以了，非常感谢。我之前试了只把clover文件夹覆盖了没解决，我又把整个EFI文件夹覆盖了，就解决了。

**Comment by ZGGSONG** [comment]
好的，一样的

**Comment by ZGGSONG** [comment]
好的

**Comment by intLyc** [comment]
我发现了规律，不是声卡驱动的问题，只要是我从windows重启切换到macos，就没有声音。如果这时候再重启还是没有声音，如果关机了再进入macos，就有声音了，我不知道为什么，很神奇。

**Comment by ZGGSONG** [comment]
我在这个readme里面说了，千万别从windows热启动到mac，否则会有意想不到的错误，当初我是爆音(我还是带着耳机的)。
