### ISSUE TITLE
更新10.15.4之后无限重启

### ISSUE THREAD

**Issue by intLyc** [ZGGSONG/HP-OMEN-15-ax214TX-Hackintosh#3]
今天更新10.15.4，安装完成了，但是再进入系统就会出现五国语言警告，继续的话会显示苹果读条，等一会又重新启动，无限循环。。。。。。

**Comment by ZGGSONG** [comment]
更新确实会碰到各种问题，建议还是全新安装比较好。
至于你说的问题，你可以吧EFI重新下载一份到U盘，使用U盘引导看是否能进入系统

**Comment by intLyc** [comment]
U盘引导也不行，我还是重装吧

**Comment by intLyc** [comment]
以后还是不轻易更新了

**Comment by ZGGSONG** [comment]
> U盘引导也不行，我还是重装吧

**Comment by ZGGSONG** [comment]
嗯嗯

**Comment by intLyc** [comment]
我问下，暗影精灵2pro，10.13.6能用驱动独显吗，如果能的话我就装这个吧

**Comment by ZGGSONG** [comment]
> 我问下，暗影精灵2pro，10.13.6能用驱动独显吗，如果能的话我就装这个吧

不行的
